// app/src/Anime.tsx
import React, { useEffect, useState } from 'react';
import { Image, StyleSheet, Text, View, DeviceEventEmitter, FlatList} from 'react-native';
import { useRoute, RouteProp } from '@react-navigation/native';
import { LinearGradient } from 'react-native-linear-gradient';
import credentials from '../credentials.json';
import { useNavigation } from '@react-navigation/native';

const urlApiGetSeason = 'http://192.168.1.172:8080/api/get_anime_season';
const urlApiGetEpisodes = 'http://192.168.1.172:8080/api/get_anime_episodes';
const base_url_tmdb = 'https://image.tmdb.org/t/p/original';

type RouteParams = {
	anime: any;
};

type Anime = {
	title: string;
	img: string;
	genre: string[];
	url: string;
};

const remote = {
	'left': 21,
	'right': 22,
	'up': 19,
	'down': 20,
	'return': 4,
	'confirm': 23,
}

const get_data_from_tmdb = async (id: string) => {
	let isMovie = false;

	id = id.replace('&', 'and');
	let url = `https://api.themoviedb.org/3/search/tv?api_key=${credentials.key_api_tmbd}&query=${id}`;
	let response = await fetch(url);
	let data = await response.json();
	let idAnime: number = data?.results.filter((result: any) => result.genre_ids.includes(16))[0]?.id;

	if (!idAnime)
	{
		isMovie = true;
		url = `https://api.themoviedb.org/3/search/movie?api_key=${credentials.key_api_tmbd}&query=${id}`;
		response = await fetch(url);
		data = await response.json();
		idAnime = data?.results.filter((result: any) => result.genre_ids.includes(16))[0]?.id;
		if (!idAnime)
		{
			console.log('no anime found');
			return (null);
		}
	}

	// get all data from the anime 
	// const url3 = `https://api.themoviedb.org/3/tv/${idAnime}?api_key=${credentials.key_api_tmbd}&language=fr-FR`;
	// const response3 = await fetch(url3);
	// const data3 = await response3.json();
	// console.log(data3);

	const url2 = `https://api.themoviedb.org/3/${isMovie ? 'movie' : 'tv'}/${idAnime}/images?api_key=${credentials.key_api_tmbd}&include_image_language=jp,en,null`;
	let response2 = await fetch(url2);
	let data2 = await response2.json();

	if (data2.logos.length === 0) {
		const fallbackUrl = `https://api.themoviedb.org/3/${isMovie ? 'movie' : 'tv'}/${idAnime}/images?api_key=${credentials.key_api_tmbd}&include_image_language=null`;
		response2 = await fetch(fallbackUrl);
		data2 = await response2.json();
	}
	return (data2);
}

const Background = ({ img }: any) => {
	return (
		<View style={{flex: 1, position: 'absolute', width: '100%', height: '100%'}}>
			{img &&
			<Image
				source={{ uri: img }}
				style={{ width: '100%', height: '100%', position: 'absolute' }}
			/>
			}
			<LinearGradient
				colors={
					['rgba(0, 0, 0, 0.9)', 'rgba(0, 0, 0, 0)']
				}
				style={styles.gradientOverlay}
				start={{ x: 0, y: 0 }}
				end={{ x: 1, y: 0 }}
			/>
		</View>
	);
}

let nbEpisodes = 0;
let listUrlEpisodes: any = null;
let allSeasons: string[] = [];

const AnimeScreen = () => {
	const route = useRoute<RouteProp<{ params: RouteParams }, 'params'>>();
	const { anime } = route.params;
	const [logo, setLogo] = useState<string>('');
	const [BackgroundImg, setBackgroundImg] = useState<string>('');
	const [genre, setGenre] = useState<string[]>([]);
	const [leftButtonSelected, setLeftButtonSelected] = useState<number>(0); // 0 = reprendre, 1 = saison, 2 = retour
	const [leftPartFocused, setLeftPartFocused] = useState<boolean>(true); // true = left, false = right
	const [needRefresh, setNeedRefresh] = useState<boolean>(false);
	
	const [epsFocused, setEpsFocused] = useState<number>(1);
	const [listEps, setListEps] = useState<number[]>([]);
	const [pageSelected, setPageSelected] = useState<number>(1);
	
	const [listSeasons, setListSeasons] = useState<string[]>([]);
	const [onSelectedSeasons, setOnSelectedSeasons] = useState<number>(0); // on season in the list without confirm
	const [showAvailableSeasons, setShowAvailableSeasons] = useState<boolean>(false);
	const [pageSelectedSeasons, setPageSelectedSeasons] = useState<number>(1);
	const [idSelectedSeason, setIdSelectedSeason] = useState<number>(0);
	const navigation = useNavigation();

	useEffect(() => {
		const	banGenre = ['vostfr', 'vf', 'cardlistanime', 'anime', '-', 'scans', 'film'];
		let		genreString :string[] = [];

		console.log(anime);
		get_data_from_tmdb(anime.title).then((data) => {
			let logoData = null;
			let i = 0;

			while (data && data.logos[i])
			{
				if (!data.logos[i].file_path.includes('svg') && data.logos[i].iso_639_1 != 'ko')
				{
					logoData = data.logos[i];
					break ;
				}
				i++;
			}
			if (logoData)
				setLogo(base_url_tmdb + logoData.file_path);
			const backdropData = data?.backdrops[0];
			if (backdropData)
				setBackgroundImg(base_url_tmdb + backdropData.file_path);
			else
				setBackgroundImg(anime.img);
		});
		anime?.genre?.map((genre: string) => {
			if (!banGenre.includes(genre.toLowerCase()))
				genreString?.push(genre); 
		});
		fetch(urlApiGetSeason, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
			},
			body: JSON.stringify({url: anime.url}),
		}).then((response) => {
			return response.json();
		}).then((data) => {
			let season = data.season;
		
			if (anime.genre.includes('Vf'))
			{
				data.season.forEach((element: string) => {
					element = element.replace('vostfr', 'vf');
					season.push(element);
				});
			}
			allSeasons = season;
			setListSeasons(allSeasons.slice(0, 12));
		}).catch((error) => {
			console.warn(error);
		});		
		setGenre(genreString);
	}, []);

	useEffect(() => {
		if (allSeasons.length == 0)
			return ;
		fetch(urlApiGetEpisodes, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
			}, 
			body: JSON.stringify({url: anime.url, season: allSeasons[idSelectedSeason]}),
		}).then((response) => {
			return response.json();
		}).then((data) => {
			nbEpisodes = data.number;
			listUrlEpisodes = data.episodes;
			if (nbEpisodes >= 12)
				setListEps([...Array(12).keys()].map(x => x + 1));
			else
				setListEps([...Array(nbEpisodes).keys()].map(x => x + 1));
		}).catch((error) => {
			console.warn(error);
		});
	}, [idSelectedSeason, listSeasons]);

	function handleKeyPress(data: any)
	{
		const keycode = data.keycode;

		if (data.screen !== 'Anime')
			return ;
		if (keycode == remote.up)
		{
			if (!leftPartFocused)
			{
				if (!showAvailableSeasons)
				{
					if (epsFocused > 1)
						setEpsFocused(epsFocused - 1);
				}
				else
				{
					if (onSelectedSeasons > 0)
						setOnSelectedSeasons(onSelectedSeasons - 1);
				}
			}
			else
			{
				if (leftButtonSelected > 0)
					setLeftButtonSelected(leftButtonSelected - 1);
			}
		}
		else if (keycode == remote.down)
		{
			if (!leftPartFocused)
			{
				if (!showAvailableSeasons)
				{
					if (epsFocused < listEps.length)
						setEpsFocused(epsFocused + 1);
				}
				else
				{
					if (onSelectedSeasons < listSeasons.length - 1)
						setOnSelectedSeasons(onSelectedSeasons + 1);
				}
			}
			else
			{
				if (leftButtonSelected < 2)
					setLeftButtonSelected(leftButtonSelected + 1);
			}
		}
		else if (keycode == remote.left)
		{
			if (!leftPartFocused)
			{
				if (pageSelected == 1 && !showAvailableSeasons)
				{
					setLeftPartFocused(true);
					setLeftButtonSelected(0);
				}
				else if (showAvailableSeasons && pageSelectedSeasons == 1)
				{
					setLeftPartFocused(true);
					setLeftButtonSelected(0);
				}
				else
				{
					if (!showAvailableSeasons)
						setPageSelected(pageSelected - 1);
					else
					{
						setPageSelectedSeasons(pageSelectedSeasons - 1);
						setListSeasons(allSeasons.slice((pageSelectedSeasons - 2) * 12, (pageSelectedSeasons - 1) * 12));
					}
				}
			}
		}
		else if (keycode == remote.right)
		{
			if (leftPartFocused)
				setLeftPartFocused(false);
			else
			{
				if (!showAvailableSeasons)
				{
					if (pageSelected < Math.ceil(nbEpisodes / 12))
					{
						setPageSelected(pageSelected + 1);
						if (pageSelected * 12 + epsFocused > nbEpisodes)
							setEpsFocused(nbEpisodes % 12);
					}
				}
				else
				{
					if (pageSelectedSeasons < Math.ceil(allSeasons.length / 12))
					{
						setPageSelectedSeasons(pageSelectedSeasons + 1);
						if (pageSelectedSeasons * 12 + onSelectedSeasons > allSeasons.length)
							setOnSelectedSeasons(allSeasons.length % 12);
						setListSeasons(allSeasons.slice(pageSelectedSeasons * 12, (pageSelectedSeasons + 1) * 12));
					}
				}
			}
		}
		else if (keycode == remote.return)
		{
			if (leftPartFocused)
				navigation.goBack();
			else
				setLeftPartFocused(true);

		}
		else if (keycode == remote.confirm)
		{
			if (leftPartFocused)
			{
				if (leftButtonSelected == 1)
				{
					setShowAvailableSeasons(!showAvailableSeasons);
					setLeftPartFocused(false);
				}
			}
			else
			{
				if (!showAvailableSeasons)
				{
					console.log('go to episode', (pageSelected - 1) * 12 + epsFocused, 'season:', allSeasons[idSelectedSeason]);
					navigation.navigate('Player', {data: {
						season: allSeasons,
						episode: (pageSelected - 1) * 12 + epsFocused,
						selectedSeasons: idSelectedSeason,
						url: anime.url,
						title: anime.title,
						listUrlEpisodes: listUrlEpisodes,
						logo: logo,
						back: anime,
					}});
				}
				else
				{
					setIdSelectedSeason((pageSelectedSeasons - 1) * 12 + onSelectedSeasons);
					setShowAvailableSeasons(!showAvailableSeasons);
					setEpsFocused(1);
				}
			}
		}
		setNeedRefresh(!needRefresh)
	}

	DeviceEventEmitter.removeAllListeners('remoteKeyPress');
	DeviceEventEmitter.addListener('remoteKeyPress', handleKeyPress);

	const NbPages = () => {
		const pages = Math.ceil(showAvailableSeasons ? allSeasons.length / 12 : nbEpisodes / 12);
		let pagesArray = [];
		for (let i = 0; i < pages; i++)
			pagesArray.push(
				<Text
					key={i}
					style={[
						styles.pageSquare,
						{
							backgroundColor: (showAvailableSeasons ? pageSelectedSeasons : pageSelected) == i + 1 ? '#fff' : '#333',
							color: (showAvailableSeasons ? pageSelectedSeasons : pageSelected) == i + 1 ? '#222' : '#fff',
						}
					]}>
					{i + 1}
				</Text>
			);
		if (pagesArray.length == 0 && !showAvailableSeasons)
			return (<Text style={styles.title}>Pas d'episodes disponibles</Text>);
		else if (pagesArray.length == 0 && showAvailableSeasons)
			return (<Text style={styles.title}>Pas de saisons disponibles</Text>);
		return (
			<View style={{width: '100%', height: 50, flexDirection: 'row', justifyContent: 'center', alignItems: 'center'}}>
				<Text></Text>
				{pagesArray.map((page) => page)}
			</View>
		);
	}

	return (
		<View style={styles.body}>
			<Background img={BackgroundImg} />
			<View style={styles.contentLeft}>
				{logo &&
				<Image source={{ uri: logo }} style={{width: 300, height: 160}} resizeMode='contain' />
				}
				<View>
					<Text style={styles.title}>{anime.title}</Text>
					<Text style={styles.genre}>{genre.join(', ')}</Text>
				</View>
				<View>
					<Text style={leftPartFocused && (leftButtonSelected == 0) ? styles.buttonSelected : styles.button}>Reprendre</Text>
					<Text style={styles.underButton}>vostfr/saison1 episode 1</Text>
				</View>
				<View>
					<Text style={leftPartFocused && (leftButtonSelected == 1)? styles.buttonSelected : styles.button}>Changer de saison</Text>
					<Text style={styles.underButton}>{allSeasons[idSelectedSeason]}</Text>
				</View>
				<View style={{flex: 1, justifyContent: 'flex-end'}}>
					<Text style={leftPartFocused && (leftButtonSelected == 2) ? styles.buttonSelected : styles.button}>Retour</Text>
				</View>
			</View>
			<View style={styles.contentRight}>
				<View style={styles.island}>
					<NbPages />
					<View style={{width: '100%', height: '100%', paddingInline: 20}}>
						{
							!showAvailableSeasons ?
							<FlatList
							data={listEps}
							renderItem={({ item }) =>
								(pageSelected - 1) * 12 + item > nbEpisodes ?
								null :
								<Text style={!leftPartFocused && epsFocused == item ? styles.epsFocused : styles.eps}>Episode {(pageSelected - 1) * 12 + item}</Text>}
							keyExtractor={(item) => item.toString()}
							/> :
							<FlatList
							data={listSeasons}
							renderItem={({ item, index }) => <Text style={!leftPartFocused && onSelectedSeasons == index ? styles.epsFocused : styles.eps}>{item}</Text>}
							keyExtractor={(item) => item}
							/>
						}
					</View>
				</View>
			</View>
		</View>
	);
};


const styles = StyleSheet.create({
	body: {
		flex: 1,
		backgroundColor: '#222',
		alignItems: 'center',
		justifyContent: 'center',
	},
	gradientOverlay: {
		...StyleSheet.absoluteFillObject,
		zIndex: 1,
	},
	contentLeft: {
		flex: 1,
		position: 'absolute',
		width: '50%',
		height: '100%',
		left: 0,
		top: 0,
		zIndex: 3,
		alignItems: 'center',
		padding: 20,
	},
	contentRight: {
		flex: 1,
		position: 'absolute',
		width: '50%',
		height: '100%',
		right: 0,
		top: 0,
		zIndex: 3,
		alignItems: 'center',
		overflow: 'hidden',
		padding: 20,
	},
	title: {
		color: '#fff',
		fontSize: 22,
		fontWeight: 'bold',
		marginTop: 10,
		textAlign: 'center',
	},
	genre: {
		color: '#ffffff90',
		fontSize: 16,
		textAlign: 'center',
	},
	button: {
		color: '#fff',
		fontSize: 20,
		fontWeight: 'bold',
		padding: 5,
		marginTop: 20,
		textAlign: 'center',
	},
	buttonSelected: {
		color: '#fff',
		fontSize: 20,
		fontWeight: 'bold',
		marginTop: 20,
		padding: 5,
		textAlign: 'center',
		backgroundColor: '#333333E0',
		borderRadius: 10,
	},
	island: {
		width: '90%',
		height: '100%',
		overflow: 'hidden',
		borderRadius: 20,
		backgroundColor: '#333333E0',
	},
	season: {
		color: '#fff',
		fontSize: 22,
		fontWeight: 'bold',
		padding: 20,
	},
	eps: {
		color: '#ffffff',
		fontSize: 18,
		padding: 5,
	},
	epsFocused: {
		color: '#ffffff',
		fontSize: 18,
		padding: 5,
		fontWeight: 'bold',
		backgroundColor: '#222',
	},
	underButton: {
		color: '#ffffff90',
		fontSize: 16,
		textAlign: 'center',
	},
	pageSquare: {
		color: '#fff',
		fontSize: 20,
		width: 30,
		borderColor: '#fff',
		borderWidth: 1,
		textAlign: 'center',
		margin: 2,
	},
});

export default AnimeScreen;

// site/src/Anime/Anime.svelte
<script lang='ts'>
	import Loader from "../Global/Loader.svelte";

	export	let		menu: any;

	const	banGenre				= ['vostfr', 'vf', 'cardlistanime', 'anime', '-', 'scans', 'film'];
	const	serverUrl				= 'http://localhost:8080';
	const	base_url_tmdb			= 'https://image.tmdb.org/t/p/original';
	const	anime					= menu.data;
	let		imageLoaded				= false;
	let		backgroundImg			= '';
	let		logoImg					= '';
	let		genreString: string[]	= [];
	let		allSeasons				= [];
	let		dataFromTmdb			= {
										title: '',
										firstAirDate: '',
										name: '',
										originalName: '',
										overview: '',
										poster: '',
										popularity: 0,
										note: 0,
										nbVotes: 0,
										noData: false,
										fetch: false
									};

	anime?.genre?.map((genre: string) => {
		if (!banGenre.includes(genre.toLowerCase()))
			genreString?.push(genre); 
	});

	const get_data_from_tmdb = async (id: string, isMovie: boolean) => {
		let allDiff: any = [];
		let response = null;
		let data = null;
		let url = null;
		let allAnimeData = [];

		if (!isMovie)
		{
			url = `https://api.themoviedb.org/3/search/tv?{api_key_tmdb}&query=${id}&language=fr-FR`;
			response = await fetch(serverUrl + '/api/tmdb', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({url: url}),
			});
			data = await response.json();
			allAnimeData = data?.results.filter((result: any) => result.genre_ids.includes(16));
		}
		else
		{
			url = `https://api.themoviedb.org/3/search/movie?{api_key_tmdb}&query=${id}&language=fr-FR`;
			response = await fetch(serverUrl + '/api/tmdb', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({url: url}),
			});
			data = await response.json();
			allAnimeData = data?.results.filter((result: any) => result.genre_ids.includes(16));
		}
		if (allAnimeData.length === 0)
		{
			dataFromTmdb.noData = true;
			dataFromTmdb.title = ''
			dataFromTmdb.firstAirDate = ''
			dataFromTmdb.name = ''
			dataFromTmdb.originalName = ''
			dataFromTmdb.overview = ''
			dataFromTmdb.poster = ''
			dataFromTmdb.popularity = 0
			dataFromTmdb.note = 0
			dataFromTmdb.nbVotes = 0
			dataFromTmdb.fetch = true;
			return (null);
		}
		console.log(allAnimeData);
		for (let i = 0; i < allAnimeData.length; i++)
			allDiff.push(allAnimeData[i][isMovie ? 'title' : 'name'].length - id.length);
		
		let animeData = allAnimeData[allDiff.indexOf(Math.min(...allDiff))];
		let idAnime: number = animeData?.id;
		
		dataFromTmdb.title = animeData.title ? animeData.title : animeData.name;
		dataFromTmdb.firstAirDate = animeData.first_air_date ? animeData.first_air_date : animeData.release_date;
		dataFromTmdb.name = animeData.name;
		dataFromTmdb.originalName = animeData.original_name;
		dataFromTmdb.overview = animeData.overview;
		dataFromTmdb.poster = base_url_tmdb + animeData.poster_path
		dataFromTmdb.popularity = animeData.popularity;
		dataFromTmdb.note = animeData.vote_average;
		dataFromTmdb.nbVotes = animeData.vote_count;
		dataFromTmdb.noData = false;

		url = `https://api.themoviedb.org/3/${isMovie ? 'movie' : 'tv'}/${idAnime}/images?{api_key_tmdb}&include_image_language=ja,en,null`;
		response = await fetch(serverUrl + '/api/tmdb', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
			},
			body: JSON.stringify({url: url}),
		});
		data = await response.json();
		if (data.logos.length === 0) 
		{
			const fallbackUrl = `https://api.themoviedb.org/3/${isMovie ? 'movie' : 'tv'}/${idAnime}/images?{api_key_tmdb}`;
			response = await fetch(serverUrl + '/api/tmdb', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({url: fallbackUrl}),
			});
			data = await response.json();
		}
		dataFromTmdb.fetch = true;
		return (data);
	}

	fetch(serverUrl + '/api/get_anime_season', {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
		},
		body: JSON.stringify({url: anime.url, serverUrl: serverUrl}),
	}).then((response) => {
		return response.json();
	}).then((data) => {
		let season = data.season;
		let isMovie = false;

		if (anime?.genre.includes('Vf'))
		{
			data.season.forEach((element: string) => {
				element = element.replace('vostfr', 'vf');
				season.push(element);
			});
		}
		allSeasons = season;
		isMovie = season[0]?.toLowerCase().includes('film');
		get_data_from_tmdb(anime.title, isMovie).then((data) => {
			if (!data)
			{
				imageLoaded = true;
				dataFromTmdb.fetch = true;
			}
			const	logoData = data?.logos[0];
			const	backdropData = data?.backdrops[0];

			if (logoData)
				logoImg = base_url_tmdb + logoData.file_path;
			if (backdropData)
				backgroundImg = base_url_tmdb + backdropData.file_path;
		});
	}).catch((error) => {
		console.warn(error);
	});

</script>

<main>
	<div class='bg-container'>
		<div class="linear-gradient"></div>
		<img
			src={anime.img}
			alt={menu.data.title}
			class='{imageLoaded && !dataFromTmdb.noData ? "hideBg" : "bg"}'
			style='z-index: 2;'
		/>
		<img
			src={backgroundImg}
			alt={menu.data.title}
			class='bg'
			on:load={() => {imageLoaded = true}}
		/>
	</div>
	{#if imageLoaded && dataFromTmdb.fetch}
		<div class="left">
			{#if logoImg}
				<img src={logoImg} alt={menu.data.title}/>
			{/if}
			<h1>{anime.title}</h1>
			<p class="genre" style="text-align: center;">{genreString.join(', ')}</p>
			{#if logoImg}
				<div class="line" style="border-top: 1px solid #fff;">
					<p class="type">Date de sortie</p>
					<p>{new Date(dataFromTmdb.firstAirDate).toLocaleDateString()}</p>
				</div>
				<div class="line">
					<p class="type">Popularité</p>
					<p>{dataFromTmdb.popularity}</p>
				</div>
				<div class="line" style="margin-bottom: 2rem;">
					<p class="type">Note</p>
					<p>{dataFromTmdb.note}/10 ({dataFromTmdb.nbVotes} votes)</p>
				</div>
				<p>{dataFromTmdb.overview}</p>
			{:else}
				<p>Aucune information disponible</p>
			{/if}
		</div>
		<div class='bg-button'>
			<button class="see-button" on:click={() => {
				menu.data = {
					anime: anime,
					tmdb: dataFromTmdb
				}
				menu.selected = 4;
			}}>Regarder</button>
		</div>
	{:else}
		<div class="center">
			<Loader scale={2} />
			<div class="center">
				<p style="margin-top: 8rem;">Chargement</p>
			</div>
		</div>
	{/if}
	
</main>

<style>
	main {
		flex: 1;
		height: 100%;
		position: relative;
	}
	.center {
		position: absolute;
		top: 50%;
		z-index: 999;
		left: 50%;
		transform: translate(-50%, -50%);
		color: #fff;
	}
	.bg-container {
		width: 100%;
		height: 100%;
		position: absolute;
		top: 0;
		left: 0;
	}
	.bg {
		width: 100%;
		height: 100%;
		background-color: rgba(0, 0, 0, 0.5);
		z-index: 0;
		object-fit: cover;
		border-top-right-radius: 0.5rem;
		border-bottom-right-radius: 0.5rem;
		object-position: center;
		position: absolute;
		top: 0;
		left: 0;
		animation: showBgAnime 0.5s;
	}
	.hideBg {
		width: 100%;
		height: 100%;
		background-color: rgba(0, 0, 0, 0.5);
		z-index: 0;
		object-fit: cover;
		border-top-right-radius: 0.5rem;
		border-bottom-right-radius: 0.5rem;
		object-position: center;
		position: absolute;
		top: 0;
		left: 0;
		animation: fadeOut 0.5s;
		opacity: 0;
	}
	.linear-gradient {
		width: 100%;
		height: 100%;
		position: absolute;
		top: 0;
		left: 0;
		z-index: 3;
		background: linear-gradient(90deg,
			rgba(51, 51, 51, 1) 0%,
			rgba(51, 51, 51, 1) 1%,
			rgba(51, 51, 51, 0.4) 50%,
			rgba(0,0,0,0) 100%
		);
	}
	.left {
		width: 50%;
		max-width: 30rem;
		height: 100%;
		position: absolute;
		top: 0;
		left: 0;
		z-index: 4;
		display: flex;
		flex-direction: column;
		align-items: center;
		color: #fff;
		padding: 2vw;
		overflow-y: scroll;
	}
	.left::-webkit-scrollbar {
		width: 0;
	}
	.left img {
		width: 100%;
		height: 10rem;
		object-fit: contain;
	}
	.left h1 {
		font-size: 1.5rem;
		margin: 1rem 0;
		text-align: center;
	}
	.left p {
		font-size: 1rem;
		text-align: justify;
	}
	.genre {
		font-size: 1rem;
		margin-bottom: 1rem;
	}
	.line {
		display: flex;
		justify-content: space-between;
		width: 90%;
		padding: 0.5rem;
		border-bottom: 1px solid #fff;
	}
	.line .type {
		font-weight: bold;
	}
	.see-button {
		background-color: #333;
		color: #fff;
		border: none;
		padding: 0.5rem 1rem;
		border-radius: 0.5rem;
		cursor: pointer;
	}

	.bg-button {
		position: absolute;
		bottom: 2rem;
		right: 2rem;
		z-index: 4;
		padding: 2px;
		border-radius: 0.5rem;
		background: linear-gradient(90deg, #333, #666, #999, #ccc, #999, #666, #333);
		animation: rotate-colors 3s linear infinite;
		background-size: 300%;
	}

	@keyframes rotate-colors {
		0% {
			background-position: 0% 50%;
		}
		50% {
			background-position: 200% 50%;
		}
		100% {
			background-position: 0% 50%;
		}
	}
</style>
